### PR TITLE
Use anaconda::libboost -> conda-forge::boost -> static linking -> remove boost dependency

### PR DESCRIPTION
**Pull request by dgehringer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dgehringer** [comment]
The idea is to change

- `conda-forge::boost` -> `anaconda::libboost`
- `conda-forge::boost-cpp` -> `anaconda::py-boost`

`anaconda::libboost` contains **libboost_*.a**, this allows static linking  and hence removes boost run dependency

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Conda-forge packages should only depend on other conda-forge packages for compatibility.

**Comment by jan-janssen** [comment]
Usually conda forge will generate the builds for the different boost versions and all you have to do is add ` {{ pin_compatible('boost-cpp') }}` to the `run` section

**Comment by dgehringer** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
