### PR TITLE
Try libcxx update

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@dgehringer Can you take a look at this PR? I am not sure why the `libcxx` restrictions were added before.

**Comment by jan-janssen** [comment]
These were added in https://github.com/conda-forge/sqsgenerator-feedstock/pull/32

**Comment by dgehringer** [comment]
Before the very recent rebuild for boost 1.82 (https://github.com/conda-forge/sqsgenerator-feedstock/pull/36), 1.78 was the pinned version from conda forge. There was a know incompatibility with (templates not defined) with 1.78 https://github.com/conda-forge/boost-cpp-feedstock/issues/134. Therefore, those restrictions were necessary to fix the pipelines. But, should have been removed in PR https://github.com/conda-forge/sqsgenerator-feedstock/pull/36

**Comment by dgehringer** [comment]
Many thanks for figuring that out

**Review by dgehringer — APPROVED** [review]
Looks fine to me

**Pull request merged**
